version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - MODE=demo
      - GOOGLE_CLOUD_PROJECT=
    volumes:
      - ./backend:/app
